apiVersion: apps/v1
kind: Deployment
metadata:
  name: odh-model-controller
spec:
  replicas: 1
  template:
    spec:
      containers:
        - args:
            - --leader-elect
            - "--monitoring-namespace"
            - "$(MONITORING_NS)"
            - --kserve-enabled
          image: $(odh-model-controller) 
          env:
            - name: MONITORING_NS
              value: kserve
          name: manager
