varReference:
  - path: metadata/name
    kind: ClusterRoleBinding
    apiGroup: authorization.openshift.io
  - path: spec/template/spec/containers[]/image
    kind: Deployment
    apiVersion: apps/v1