---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base

patchesJson6902:
- target:
    kind: DeploymentConfig
    version: v1
    group: apps.openshift.io
    name: jupyterhub
  path: jupyterhub-patch.yaml
