kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rhods-namespace-read
subjects:
  - kind: ServiceAccount
    name: prometheus-custom
    namespace: redhat-ods-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rhods-namespace-read
