kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: jupyterhub
  name: jupyterhub-deployer
rules:
  - verbs:
      - get
      - watch
      - list
      - delete
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
      - watch
      - list
      - patch
    apiGroups:
      - ''
    resources:
      - replicationcontrollers/scale
