apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: jupyterhub-ha-sidecar
  name: sidecar-probe
data:
  probe.sh: |
    function get_leader() {
        echo "$(curl http://localhost:4040 2> /dev/null | grep -Eo '"name"[^,]*' | grep -Eo '[^:]*$')"
    };
    function is_empty_string() {
        # When the sidecar container is not working the name of the leader is an empty string
        [ "$(get_leader)" == "" ]
    };
    if is_empty_string; then
        # Sidecar container is returning an empty string, there must be a problem
        exit 1
    else
        # Pod is working, we can exit with success
        exit 0
    fi