apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- jupyterhub-configmap.yaml
- jupyterhub-secret.yaml
- jupyterhub-dc.yaml
- jupyterhub-service.yaml
- jupyterhub-serviceaccount.yaml
- jupyterhub-role.yaml
- jupyterhub-rolebinding.yaml
- jupyterhub-cluster-role.yaml
- jupyterhub-cluster-rolebinding.yaml
- jupyterhub-monitoring-rolebinding.yaml
- jupyterhub-route.yaml
- jupyterhub-singleuser-profiles-configmap.yaml
- jupyterhub-spark-operator-configmap.yaml
- jupyterhub-groups-configmap.yaml
- jupyterhub-notebook-image-puller-rb.yaml
- jupyterhub-deployer-role.yaml
- jupyterhub-deployer-rolebinding.yaml
- traefik-credentials-secret.yaml
- traefik-configmap.yaml
- traefik-deployment.yaml
- traefik-role.yaml
- traefik-rolebinding.yaml
- traefik-serviceaccount.yaml
- traefik-service.yaml
- groups-config.yaml

commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: jupyterhub

configMapGenerator:
- name: parameters
  envs: 
    - params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: namespace
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.namespace
- name: storage_class
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.storage_class
- name: s3_endpoint_url
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.s3_endpoint_url
- name: jupyterhub_groups_config
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.jupyterhub_groups_config
- name: jupyterhub_secret
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.jupyterhub_secret
- name: notebook_destination
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.notebook_destination
- name: traefik_credentials_secret
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.traefik_credentials_secret
- name: jupyterhub_rds_secret
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.jupyterhub_rds_secret
configurations:
- params.yaml
